name: CI

on:
  push:
    branches:
      - main
      - actions-strike-back
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.6.7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check
        run: pnpm run check

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.6.7
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.1
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare
        run: pnpm playwright install

      - name: Test
        run: |
          pnpm run test
